#!/usr/bin/env python3
"""
wav_to_wavetable.py
───────────────────
Převod WAV souboru na C wavetable pro Arduino Due / BareMetalCore.

Výstupní formát:
    const int16_t <name>[2048u] = { ... };  // hodnoty v [-2048, 2047]

Rozsah hodnot plyne přímo z ISR v BareMetalCore.cpp:
    mix += (int32_t(sample) * v.amplitude) >> 12;
    → při amplitude=4095 a sample=2047: příspěvek = 2046, DAC = 4094 ✓

Závislosti: pip install numpy scipy
"""

import argparse
import sys
import textwrap
from pathlib import Path

import numpy as np
from scipy.io import wavfile
from scipy.signal import resample


# ─── Konstanty odpovídají BareMetalCore.h ───────────────────────────────────
WAVETABLE_SIZE = 2048          # BMC_WAVETABLE_SIZE  (= 2^11)
SAMPLE_MIN     = -2048         # int16 uložené jako 12-bit signed
SAMPLE_MAX     =  2047
VALUES_PER_LINE = 16           # šířka výstupu


# ─── Pomocné funkce ──────────────────────────────────────────────────────────

def load_wav(path: Path) -> tuple[int, np.ndarray]:
    """
    Načte WAV a vrátí (sample_rate, mono_float32).
    Podporuje 8, 16, 24, 32 bit PCM i float32.
    Stereo → průměr kanálů.
    """
    rate, data = wavfile.read(path)

    # Převod na float64, rozsah [-1.0, 1.0]
    if data.dtype == np.uint8:                     # 8-bit WAV je unsigned
        data = (data.astype(np.float64) - 128.0) / 128.0
    elif data.dtype == np.int16:
        data = data.astype(np.float64) / 32768.0
    elif data.dtype == np.int32:
        data = data.astype(np.float64) / 2147483648.0
    elif data.dtype == np.float32:
        data = data.astype(np.float64)
    else:
        raise TypeError(f"Nepodporovaný formát WAV: {data.dtype}")

    # Stereo → mono (průměr L+R)
    if data.ndim == 2:
        print(f"  [info] Stereo → mono (průměr {data.shape[1]} kanálů)")
        data = data.mean(axis=1)

    return rate, data


def resample_to_wavetable(data: np.ndarray, src_rate: int,
                           one_cycle_only: bool) -> np.ndarray:
    """
    Resampluje vstupní data na přesně WAVETABLE_SIZE vzorků.

    one_cycle_only=True:  vezme pouze první periodu (vhodné pro syntetické tvary).
    one_cycle_only=False: vezme celý soubor (vhodné pro textury / perkuse).
    """
    if one_cycle_only:
        # Vezme jen tolik vzorků, kolik odpovídá jedné základní periodě.
        # Heuristika: první nulový přechod → nahoru po začátku.
        data = _extract_first_cycle(data, src_rate)

    # scipy.signal.resample → Fourierova metoda (zachovává spektrum)
    resampled = resample(data, WAVETABLE_SIZE)
    return resampled


def _extract_first_cycle(data: np.ndarray, rate: int) -> np.ndarray:
    """
    Pokusí se izolovat jednu periodu pomocí autokorelace.
    Selže-li, vrátí data beze změny (resample zvládne i celý soubor).
    """
    # Autokorelace na prvních 0.1 s (max 4410 vzorků)
    window = min(len(data), rate // 10)
    snippet = data[:window]
    corr = np.correlate(snippet, snippet, mode='full')
    corr = corr[len(corr) // 2:]          # jen kladná část

    # Hledáme první lokální maximum MIMO nulu (lag > 10 vzorků)
    for lag in range(10, len(corr) - 1):
        if corr[lag] > corr[lag - 1] and corr[lag] > corr[lag + 1]:
            if corr[lag] > 0.4 * corr[0]: # musí být silná korelace
                print(f"  [info] Autokorelace: perioda ≈ {lag} vzorků "
                      f"({rate / lag:.1f} Hz)")
                return data[:lag]
    print("  [warn] Perioda nenalezena, používám celý soubor.")
    return data


def normalize_to_12bit(data: np.ndarray, headroom_db: float) -> np.ndarray:
    """
    Normalizuje na rozsah [-2048, 2047] s volitelným headroomem.
    headroom_db = 0  → plná amplituda (|peak| = 2047)
    headroom_db = 6  → -6 dBFS (|peak| ≈ 1024)
    """
    peak = np.max(np.abs(data))
    if peak < 1e-9:
        raise ValueError("Vstupní signál je tichý (peak ≈ 0).")

    gain = 10 ** (-headroom_db / 20.0)          # lineární koeficient
    normalized = data / peak * SAMPLE_MAX * gain

    # Tvrdý clip (pro jistotu po float operacích)
    normalized = np.clip(normalized, SAMPLE_MIN, SAMPLE_MAX)
    return normalized.astype(np.int16)


def format_c_array(samples: np.ndarray, name: str,
                   source_file: str, extra_comment: str) -> str:
    """
    Generuje C deklaraci:
        const int16_t <name>[2048u] = { ... };
    """
    assert len(samples) == WAVETABLE_SIZE

    # Záhlaví
    lines = [
        f"/* Auto-generated by wav_to_wavetable.py",
        f" * Source : {source_file}",
    ]
    if extra_comment:
        lines.append(f" * Note   : {extra_comment}")
    lines += [
        f" * Size   : {WAVETABLE_SIZE} samples  (int16, range [{SAMPLE_MIN}, {SAMPLE_MAX}])",
        f" * Usage  : BMC_TABLES index or standalone noteOn() wavetable",
        f" */",
        f"const int16_t {name}[{WAVETABLE_SIZE}u] = {{",
    ]

    # Tělo — VALUES_PER_LINE hodnot na řádek
    for i in range(0, WAVETABLE_SIZE, VALUES_PER_LINE):
        chunk = samples[i : i + VALUES_PER_LINE]
        row   = ", ".join(f"{v:6d}" for v in chunk)
        comma = "," if (i + VALUES_PER_LINE) < WAVETABLE_SIZE else ""
        lines.append(f"    {row}{comma}")

    lines.append("};")
    return "\n".join(lines)


def dc_remove(data: np.ndarray) -> np.ndarray:
    """Odstraní DC offset (střední hodnotu) před normalizací."""
    dc = np.mean(data)
    if abs(dc) > 0.01:
        print(f"  [info] DC offset odstraněn: {dc:.4f}")
    return data - dc


# ─── CLI ─────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description="WAV → C wavetable (int16, 2048 vzorků) pro BareMetalCore",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Příklady:
              # Jednoduchý převod, výstup na stdout
              python wav_to_wavetable.py sine_A4.wav

              # Uložení do souboru, vlastní název pole
              python wav_to_wavetable.py kick.wav -o kick_wave.h -n kick_table

              # Celý soubor (perkuse), -6 dB headroom
              python wav_to_wavetable.py cymbal.wav --full --headroom 6
        """)
    )
    p.add_argument("input",          type=Path,  help="Vstupní WAV soubor")
    p.add_argument("-o", "--output", type=Path,  default=None,
                   help="Výstupní .h soubor (výchozí: stdout)")
    p.add_argument("-n", "--name",   type=str,   default=None,
                   help="Název C pole (výchozí: odvozeno z názvu souboru)")
    p.add_argument("--full",         action="store_true",
                   help="Použít celý WAV (výchozí: jen první perioda)")
    p.add_argument("--headroom",     type=float, default=0.0,
                   help="Headroom v dB pod plnou škálou (výchozí: 0)")
    p.add_argument("--no-dc",        action="store_true",
                   help="Přeskočit odstranění DC offsetu")
    p.add_argument("--comment",      type=str,   default="",
                   help="Volitelný komentář do záhlaví")
    return p.parse_args()


def sanitize_name(path: Path) -> str:
    """'kick drum 01.wav' → 'kick_drum_01'"""
    stem = path.stem
    name = "".join(c if (c.isalnum() or c == "_") else "_" for c in stem)
    if name[0].isdigit():
        name = "wt_" + name
    return name.lower()


# ─── Hlavní tok ──────────────────────────────────────────────────────────────

def main():
    args = parse_args()

    if not args.input.exists():
        print(f"Chyba: soubor '{args.input}' nenalezen.", file=sys.stderr)
        sys.exit(1)

    print(f"Načítám: {args.input}")
    rate, data = load_wav(args.input)
    print(f"  Sample rate : {rate} Hz")
    print(f"  Délka       : {len(data)} vzorků ({len(data)/rate*1000:.1f} ms)")

    if not args.no_dc:
        data = dc_remove(data)

    one_cycle = not args.full
    data = resample_to_wavetable(data, rate, one_cycle_only=one_cycle)
    print(f"  Resample    : → {len(data)} vzorků (wavetable)")

    samples = normalize_to_12bit(data, args.headroom)
    actual_peak = int(np.max(np.abs(samples)))
    print(f"  Peak        : {actual_peak} / {SAMPLE_MAX}  "
          f"({actual_peak/SAMPLE_MAX*100:.1f} %FS)")

    name   = args.name or sanitize_name(args.input)
    output = format_c_array(samples, name, str(args.input), args.comment)

    if args.output:
        args.output.write_text(output + "\n", encoding="utf-8")
        print(f"Zapsáno: {args.output}  ({args.output.stat().st_size} B)")
    else:
        print()
        print(output)


if __name__ == "__main__":
    main()
